// app/layout.tsx or _app.tsx
import { Geist, Geist_Mono } from "next/font/google";
import './globals.css';  // Import the global styles

// Initialize the custom fonts from Google Fonts
const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

// Metadata (this will be added in the head of the document)
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Root Layout Component
export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased font-sans`} // Using custom fonts
      >
        {children}  {/* This is where all your content will be rendered */}
      </body>
    </html>
  );
}
